# Generated by Django 5.2.4 on 2025-07-07 17:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NGO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Official name of the NGO', max_length=200)),
                ('description', models.TextField(help_text="Brief description of NGO's mission and activities")),
                ('category', models.CharField(choices=[('education', 'Education'), ('healthcare', 'Healthcare'), ('environment', 'Environment'), ('poverty', 'Poverty Alleviation'), ('women_empowerment', 'Women Empowerment'), ('child_welfare', 'Child Welfare'), ('disaster_relief', 'Disaster Relief'), ('other', 'Other')], default='other', max_length=50)),
                ('website', models.URLField(blank=True, help_text='Official website URL', null=True)),
                ('phone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(max_length=254)),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(default='India', max_length=100)),
                ('registration_number', models.CharField(help_text='Official registration number', max_length=100, unique=True)),
                ('registration_date', models.DateField(help_text='Date of official registration')),
                ('tax_exempt_number', models.CharField(blank=True, help_text='Tax exemption number if applicable', max_length=100, null=True)),
                ('founding_year', models.IntegerField(help_text='Year the NGO was founded')),
                ('employee_count', models.IntegerField(help_text='Approximate number of employees')),
                ('annual_budget', models.DecimalField(decimal_places=2, help_text='Annual budget in INR', max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'NGO',
                'verbose_name_plural': 'NGOs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NGODocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('registration_certificate', 'Registration Certificate'), ('tax_exemption', 'Tax Exemption Certificate'), ('annual_report', 'Annual Report'), ('financial_statement', 'Financial Statement'), ('other', 'Other')], max_length=50)),
                ('document_name', models.CharField(max_length=255)),
                ('document_file', models.FileField(help_text='Upload relevant documents', upload_to='ngo_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('ngo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='ngo_registration.ngo')),
            ],
            options={
                'verbose_name': 'NGO Document',
                'verbose_name_plural': 'NGO Documents',
            },
        ),
    ]
