# Generated by Django 5.2.4 on 2025-07-09 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NGO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('registration_number', models.CharField(max_length=100)),
                ('date_of_establishment', models.DateField()),
                ('ngo_type', models.CharField(max_length=100)),
                ('contact_person', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('areas_of_work', models.CharField(choices=[('Education', 'Education'), ('Health', 'Health'), ('Women Empowerment', 'Women Empowerment'), ('Skill Development', 'Skill Development'), ('Environment', 'Environment'), ('Livelihood', 'Livelihood'), ('Other', 'Other')], default='Other', max_length=500)),
                ('registration_certificate', models.FileField(upload_to='ngo_certificates/')),
                ('password', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
