# Generated by Django 5.1.3 on 2025-07-09 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NGOs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaOfWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='ngo',
            name='areas_of_work',
        ),
        migrations.AddField(
            model_name='ngo',
            name='areas_of_work',
            field=models.ManyToManyField(blank=True, to='NGOs.areaofwork'),
        ),
    ]
