# Generated by Django 5.2.4 on 2025-07-09 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ideas", "0002_digilockerprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="idea",
            name="report",
            field=models.TextField(blank=True, null=True),
        ),
    ]
