# Generated by Django 5.2.4 on 2025-07-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ideas", "0003_idea_report"),
    ]

    operations = [
        migrations.AlterField(
            model_name="idea",
            name="audio_file",
            field=models.FileField(blank=True, null=True, upload_to="voices/"),
        ),
    ]
