# Generated by Django 5.2.3 on 2025-07-05 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheme',
            old_name='eligibility_criteria',
            new_name='eligibility',
        ),
        migrations.RemoveField(
            model_name='scheme',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='scheme',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='scheme',
            name='language',
            field=models.CharField(max_length=50),
        ),
    ]
